mutation createWorkerCategories(
	$objects: [worker_category_insert_input!]!,
) {
	insert_worker_category(objects: $objects) {
		returning {
			categoryId: category_id,
			workerId: worker_id,
		}
	}
}
