query getWorkers($categoryIds: [Int!]) {
	worker(limit: 50, order_by: {id: asc}, where: {worker_categories: {category_id: {_in: $categoryIds}}}) {
		id
		first_name
		last_name
		description
#		worker_categories {
#			category {
#				id
#				name
#			}
#		}
	}
}
